apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  namespace: gmail-upload
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/gmail-uploads
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: gmail-upload
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 